config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :diplomats do
    resources :roles
  end

  get '/roles', to: 'roles#list'
  root 'diplomats#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :diplomats, through: :roles
end

app/models/country_relation.rb
class CountryRelation < ApplicationRecord
  belongs_to :country
  belongs_to :diplomat
end

app/models/diplomat.rb
class Diplomat < ApplicationRecord
  has_many :roles

  def contemporaries
    Diplomat.where("born between '?' and '?'", born.to_i - 5, born.to_i + 5)
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :diplomat


  def siblings
    Role.where(role_name: role_name)
  end
end

app/models/xml_loader.rb
class XmlLoader

  def initialize
    @doc = File.open("foo.xml") { |f| Nokogiri::XML(f) }
  end

  def load_section_1_entries
    section_1_entries
      .select{ |entry| entry.css('date').first }
      .map do |entry|
      # There are 46 entries in the data where there is no date for the person
      # and instead there is a reference to another name, I don't know what this is
      # supposed to represent so I'm excluding those.

        diplomat = Diplomat.create({
          name: entry.css('persName').text,
          born: entry.css('date').first.attribute('from').try(:value),
          died: entry.css('date').first.attribute('to').try(:value)
        })

        roles = entry.css('seg').map do |seg|
          Role.create({
            role_name: seg.css('rs').text,
            start_date: seg.css('date').first.attribute('from').try(:value),
            end_date: seg.css('date').first.attribute('to').try(:value),
            diplomat: diplomat
          })
        end
    end
  end

  def section_1_entries
    @section_1_entries ||= @doc.css('div[type="entry_list"]').css('entry')
  end

  def load_section_2_entries
    diplomats = Diplomat.all

    countries.each do |c|
      # c.css('head').first}.compact.map{|h| Country.create name:h.text }
      diplomat_names = c.css('persName').text
      diplomat_names.each do |n|
        chunks = n.split(' ').select { |na| na.size > 3 }
        chunks.each do |chunk|
          possibles = diplomats.select { |d| d.name.include? chunk }

        end
      end
    end
  end

  def section_2_entries
    @section_2_entries ||= @doc.css('div[type="countries_section"]').css('div[type="subsection"]').first
  end

  ## gets the div node that represents a country
  def country_heads
    section_2_entries
      .children
      .select{|d| d.name='div'}
      .map{|n| n.css('head')}
      .reject{|f| f.empty? }
      .map{ |n| n.first.parent}
  end

  def countries
    a = country_heads.first
    @countries = []
    while a do
      a = a.next_element
      @countries << a if a && a.name =='div'
    end
    @countries
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    render json: Countries.all.to_json
  end
end

app/controllers/diplomats_controller.rb
class DiplomatsController < ApplicationController
  def index
    render json: Diplomat.all.to_json
  end

  def roles
    render json: Role.all.to_json
  end

  def show

    @diplomat = Diplomat.find( params["id"])
  end

  def list
    search_term = params['q']
    if search_term
      @diplomats = Diplomat.where(" UPPER(name) like ?", '%' + search_term.upcase + '%')
    else
      @diplomats = Diplomat.all
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  def index
    @diplomat = Diplomat.find params["diplomat_id"]
    render json: @diplomat.roles.map(&:to_json)
  end

  def list
    @roles = Role.all
  end

  def show

    @siblings = Role.find(params['id']).siblings
    dates =
      @siblings
        .select {|s| s.start_date && s.end_date }
        .map{ |s| s.end_date.to_f - s.start_date.to_f }
    @tenure = dates.sum / dates.length
  end
end

app/views/diplomats/list.html.erb
<div class = "container">
  <h1> A list of all of the diplomats </h1>


  <table class='table'>
    <thead>
      <th>Role</th>
      <th> Born </th>
      <th>Died</th>
    </thead>

    <tbody>
      <% @diplomats.each do |d| %>
        <tr>
          <td>
            <%=link_to d.name, diplomat_path(d)%>
          </td>
          <td>
            <%=d.born%>
          </td>
          <td>
            <%=d.died%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/diplomats/show.html.erb
<div class = "container">

  <h1>
    Find out more about a diplomat
  </h1>

  <h2> a list of roles held by <%= @diplomat.name %>  (<%= @diplomat.born %> - <%= @diplomat.died %>)</h1>

  <div class='panel'>
    <table class='table'>
      <thead>
        <th>Role</th>
        <th>Age at start </th>
        <th>Start Date</th>
        <th>End Date</th>
      </thead>

      <tbody>
        <% @diplomat.roles.each do |role| %>
          <tr>
            <td>
              <a href="/diplomats/<%= @diplomat.id %>/roles/<%= role.id %>"><%= role.role_name %></a>
            </td>
            <td>
              <% if @diplomat.born && role.start_date %>
                <%= role.start_date.to_i - @diplomat.born.to_i %>
              <% else %>
                unknown
              <% end %>
            </td>
            <td>
              <%= role.start_date %>
            </td>
            <td>
              <%= role.end_date %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <h2> Contemporaries </h2>
  <p> a list of people whose were born within 5 years of this diplomat being born </p>
  <% @diplomat.contemporaries.each do |c| %>
    <a href='/diplomats/<%=c.id%>'> <%= c.name %> </a> born in <%= c.born %> <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyFullstackTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <div class='container'>
      <nav>
        <%= form_tag('/', method:'GET') do %>
          Search for a Diplomat by name <%= text_field_tag :q %>
          <%= submit_tag 'Search' %>
        <% end %>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/roles/list.html.erb
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<div class = "container">
  <h1> List of roles </h1>

  <table class='table'>
    <thead>
      <th>Role</th>
      <th> Age at start </th>
      <th>Start Date</th>
      <th>End Date</th>
    </thead>

    <tbody>
      <% @diplomat.roles.each do |role| %>
        <tr>
          <td>
            <%= role.role_name %>
          </td>
          <td>
            <% if @diplomat.born && role.start_date %>
              <%= role.start_date.to_i - @diplomat.born.to_i %>
            <% else %>
              unknown
            <% end %>
          </td>
          <td>
            <%= role.start_date %>
          </td>
          <td>
            <%= role.end_date %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/roles/show.html.erb
<div class = "container">
  <h1> <%= @siblings.first.role_name%> </h1>


  average tenure
  <%= @tenure.round  %> years
  <table class='table'>
    <thead>
      <th>Diplomat</th>
      <th> Age at start </th>
      <th>Start date </th>
      <th>End Date</th>
    </thead>

    <tbody>
      <% @siblings.sort {|a,b| a.start_date.to_i <=> b.start_date.to_i}.each do |s| %>
        <tr>
          <td>
            <a href="/diplomats/<%= s.diplomat.id %>"><%= s.diplomat.name %></a>
          </td>

          <td>
            <% if s.diplomat.born && s.start_date %>
              <%= s.start_date.to_i - s.diplomat.born.to_i %>
            <% else %>
              unknown
            <% end %>
          </td>

          <td>
            <%= s.start_date %>
          </td>

          <td>
            <%= s.end_date %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>